### ISSUE TITLE
Problem with IE11 Edge

### ISSUE THREAD

**Issue by Kiraya** [benmarch/hone-bower#1]
Hi, using Hone with Angular-ui-tour, we have a problem with IE11 browser.
some elements return as to be "[object SVGAnimatedString] "and not a simple element, so on IE, there are restrictions to access Classnam attribute. The solution we found is to add this check when you try to write on className Attr. There is the same problem with removeClass.

   if (t.classList) {
        t.classList.add(e);
    } else {
        if (t.className.toString() === '[object SVGAnimatedString]') {
            t.className.baseVal += (t.className.baseVal.length ? " " : "") + e;
        } else {
            t.className += (t.className.length ? " " : "") + e;
        }
    }

**Comment by benmarch** [comment]
Hi @Kiraya,

Thank you for discovering and solving this issue! I will update both Hone and Angular UI Tour later today.

Thanks,
Ben

**Comment by benmarch** [comment]
Updated. Hone @ 1.0.3, Angular UI Tour @ 0.8.1. Thanks for the PR!!
